"""add scope to refresh_tokens

Revision ID: 7cd69cccf8bb
Revises: dc991ca0bc5f
Create Date: 2026-09-26 16:53:31.291533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cd69cccf8bb'
down_revision: Union[str, Sequence[str], None] = 'dc991ca0bc5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('scope', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'scope')
    # ### end Alembic commands ###
