"""add user pools

Revision ID: c8c72b01f504
Revises: 7cd69cccf8bb
Create Date: 2026-09-26 17:13:17.570517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8c72b01f504'
down_revision: Union[str, Sequence[str], None] = '7cd69cccf8bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_pools',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('clients', sa.Column('user_pool_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_clients_user_pool_id'), 'clients', ['user_pool_id'], unique=False)
    op.create_foreign_key('fk_clients_user_pool_id_user_pools', 'clients', 'user_pools', ['user_pool_id'], ['id'])
    op.add_column('users', sa.Column('user_pool_id', sa.Uuid(), nullable=False))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_user_pool_id'), 'users', ['user_pool_id'], unique=False)
    op.create_unique_constraint('uq_users_pool_email', 'users', ['user_pool_id', 'email'])
    op.create_foreign_key('fk_users_user_pool_id_user_pools', 'users', 'user_pools', ['user_pool_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_user_pool_id_user_pools', 'users', type_='foreignkey')
    op.drop_constraint('uq_users_pool_email', 'users', type_='unique')
    op.drop_index(op.f('ix_users_user_pool_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'user_pool_id')
    op.drop_constraint('fk_clients_user_pool_id_user_pools', 'clients', type_='foreignkey')
    op.drop_index(op.f('ix_clients_user_pool_id'), table_name='clients')
    op.drop_column('clients', 'user_pool_id')
    op.drop_table('user_pools')
    # ### end Alembic commands ###
